name: Data link to OxCGRT
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Download raw csv from OxCGRT database
        run: |
          curl -s 'https://ocgptweb.azurewebsites.net/CSVDownload?type=Compressed' > data/OxCGRT_latest.csv
          curl -s 'https://ocgptweb.azurewebsites.net/CSVDownload' > data/OxCGRT_latest_withnotes.csv
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Pull latest OxCGRT data" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
