name: Get latest data from OxCGRT
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Download raw csv from OxCGRT database
        run: curl -s 'https://ocgptweb.azurewebsites.net/CSVDownload?type=Compressed' > data/data.csv
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updating data file" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
